выполнил задание по html
NikulinOlegDmitrievich/juniors-way pull request #1
Opened 2018-05-24 20:57 UTC by NikulinOlegDmitrievich

2018-05-28 16:45 UTC, web-crab requested changes
1. после и перед тегами не нужны пробелы
2. пустой строкой можно разделять только дочерние блоки между собой и строка должна быть одна

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +            <ol>
списки не могут быть дочерними элементами `p`

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +                <caption> Сравнительная таблица</caption>
`caption` должен быть дочерним элементом `table`

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +                    <td style="text-align: center"><u>ВИКИПЕДИЯ</u></td>
это оглавление колонок, значит должен быть тег `th` а не `td` и весь `tr` должен быть в `thead`

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +                    <td class="col1" style="text-align: center">120 км/ч</td>
км/ч должен быть сверху, в виде верхнего индекса

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +                    <td class="col1" style="text-align: center"><a target="_blanck" href="https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BF%D0%B0%D1%80%D0%B4">Перейти</a></td>
_blanck -> _blank

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +           </article>
`article` не может быть дочерним элементом `table`, ими могут быть только теги `caption, thead, tbody, tfoot`

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +                    «Любое животное после определенной порции любви и тепла становится ручным. Люди же от любви <br>
для цитаты и ее автора есть специальные теги

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +                <legend>
пропущен таб

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +                  <label for="user name"> Имя</label> <br>
не используй пробел. никогда. ни для названия папок ни для атрибутов. нигде

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +                  <label for="women"> Женщина</label> <br>
одна из радиокнопок должна быть выбрана сразу при загрузке страницы

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +                <h1>Автор Никулин О.Д.</h1>
h1 может быть только один на странице

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +            <article>
это не статья, здесть article лишний

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +           <article>
тег article должен обрамлять весь контент статьи

2018-05-28 16:45 UTC, klimash commented on html task/Rabota_po_html.html
> +        <h1> Самые быстрые животные в мире</h1>
все содержимое `body` должно быть в теге `main`

2018-05-28 17:12 UTC, NikulinOlegDmitrievich commented on html task/Rabota_po_html.html
> +                    <td style="text-align: center"><u>ВИКИПЕДИЯ</u></td>
1

2018-05-28 17:34 UTC, NikulinOlegDmitrievich commented on html task/Rabota_po_html.html
> +                  <label for="women"> Женщина</label> <br>
1

2018-05-28 19:31 UTC, NikulinOlegDmitrievich commented on html task/Rabota_po_html.html
> +            <ol>
1

2018-05-28 19:31 UTC, NikulinOlegDmitrievich commented on html task/Rabota_po_html.html
> +                <caption> Сравнительная таблица</caption>
1

2018-05-28 19:31 UTC, NikulinOlegDmitrievich commented on html task/Rabota_po_html.html
> +                    <td style="text-align: center"><u>ВИКИПЕДИЯ</u></td>
1

2018-05-28 19:31 UTC, NikulinOlegDmitrievich commented on html task/Rabota_po_html.html
> +                    <td class="col1" style="text-align: center">120 км/ч</td>
1

2018-05-28 19:32 UTC, NikulinOlegDmitrievich commented on html task/Rabota_po_html.html
> +                    <td class="col1" style="text-align: center"><a target="_blanck" href="https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BF%D0%B0%D1%80%D0%B4">Перейти</a></td>
1

2018-05-28 21:10 UTC, web-crab requested changes
сделай лейблы для элементов формы следующим образом:
`<label>
    Имя<br>
    <input>
</label>`
таким образом не нужно задавать id и for

2018-05-28 21:10 UTC, web-crab commented on html task/Rabota_po_html.html
> +                <h1> Самые быстрые животные в мире</h1>
лишний пробел после тега

2018-05-28 21:10 UTC, web-crab commented on html task/Rabota_po_html.html
> +                    Ну конечно, вы скажете: <strong> гепард</strong>. И будете правы! <strong><em>Он самый быстрый из живущих на суше</em></strong>. Сего- <br>
`<strong> гепард` - тут лишний пробел

2018-05-28 21:10 UTC, web-crab commented on html task/Rabota_po_html.html
> +                    Сегодня мы рассмотрим следующих представителей фауны: <br>
зачем перенос строки, если дальше ничего нет?) перед br тоже не нужен пробел

2018-05-28 21:10 UTC, web-crab commented on html task/Rabota_po_html.html
> +                    <caption> Сравнительная таблица</caption>
не нужен пробел после тега

2018-05-28 21:10 UTC, web-crab commented on html task/Rabota_po_html.html
> +                            <td style="text-align: center"><u>ВИКИПЕДИЯ</u></td>
td -> th, похуй на жироту

2018-05-28 21:10 UTC, web-crab commented on html task/Rabota_po_html.html
> +                            <td class="col1" style="text-align: center">120 <sup>км/ч</sup></td>
после числа не нужен пробел

2018-05-28 21:10 UTC, web-crab commented on html task/Rabota_po_html.html
> +                        составлять не менее 300 км/ч! Это рекорд для наземных насекомых. <br> <br>
зачем двойной перенос строки, если после него ничего нет?

2018-05-28 21:10 UTC, klimash commented on html task/Rabota_po_html.html
> +                        <input type="text" id="user name" placeholder=" Введите свое имя" maxlength=" 15" minlength="3"> <br>
id="user name" -> id="user_name". не используй в атрибутах пробелы. разумеется, кроме плейсхолдера. когда ты напишешь class="one two three" то это будет три разных класса

2018-05-28 21:10 UTC, klimash commented on html task/Rabota_po_html.html
> +                        <label for="user patronymic"> отчество</label> <br>
тут как и везде между тегом и контентом пробел лишний

2018-05-28 21:10 UTC, klimash commented on html task/Rabota_po_html.html
> +            <address>
пропущен таб

2018-05-28 21:10 UTC, klimash commented on html task/Rabota_po_html.html
> +                    <p>
лишний таб

2018-05-28 21:10 UTC, klimash commented on html task/Rabota_po_html.html
> +                    <blockquote>
лишний таб

2018-05-28 21:10 UTC, klimash commented on html task/Rabota_po_html.html
> +                        <label for="#"> Ваше хобби:</label> <br>
в for не указано, к чему относится label

2018-05-28 21:10 UTC, klimash commented on html task/Rabota_po_html.html
> +                        <label for="#"> О чем написать следуйщую статью:</label> <br>
в for не указано, к чему относится label

2018-05-29 19:44 UTC, web-crab approved these changes

2018-05-29 19:44 UTC, merged